#Stage 02
Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "10.0.0.10 master-node" >> /etc/hosts
        echo "10.0.0.11 worker-node01" >> /etc/hosts
        echo "10.0.0.12 worker-node02" >> /etc/hosts
    SHELL
    
    config.vm.box = "bento/ubuntu-21.10"
    
    # Master-node definition
    config.vm.define "master" do |master|

        master.vm.hostname = "master-node"
        master.vm.network "private_network", ip: "10.0.0.10"
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end

    config.vm.define "node01" do |node1|
      node1.vm.hostname = "worker-node01"
      node1.vm.network "private_network", ip: "10.0.0.11"
      node1.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 1
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end

    config.vm.define "node02" do |node2|
        node2.vm.hostname = "worker-node02"
        node2.vm.network "private_network", ip: "10.0.0.12"
        node2.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
      end
end
