#Stage 01 
Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "10.0.0.10 master-node" >> /etc/hosts
    SHELL
    
    config.vm.box = "bento/ubuntu-21.10"
    
    # Master-node definition
    config.vm.define "master" do |master|

        master.vm.hostname = "master-node"
        master.vm.network "private_network", ip: "10.0.0.10"
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
    end
end
